
export interface leadListModel{
  lead_owner:string,
  company:string,
  first_name:string,
  last_name:string,
  title:string,
  email:string,
  fax:string,
  phone:string,
  mobile:string,
  website:string,
  lead_source:string,
  lead_status:string,
  image_url:string,
  industry:string,
  no_of_employees:string|number,
  annual_revenue:string|number,
  rating:string|number,
  email_opt_out:string|number,
  skype_id:string,
  secondary_email:string,
  twitter:string,
  street:string,
  city:string,
  state:string,
  zipcode:string,
  country:string,
  description:string,
  created_by:string,
  lead_code?: string,
  campaign_code?: string,
  campaign_name?: string,
  is_ui_query?: number,
  middle_query?: string
}