import { Injectable } from '@angular/core';
import { leadListModel } from 'app/model/LeadsModel';
import { BehaviorSubject } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class LeadsService {

  leadLists: BehaviorSubject<any> = new BehaviorSubject<any>(null); 
  constructor() {
    this.leadLists.next([
      {
        lead_owner:'User',
        company: 'pristine Isdkf df',
        f_name: 'Anonyms',
        l_name:'Hsjieb',
        title:'Tech Head',
        email: 'abcdefg23@kjdfd.com',
        phone:'1234567890',
        fax:'',
        mobile_no: '8949394747',
        website:'www.jfgjfnf.com',
        
      }
    ])
  }

  createLead(values){
    let json={
      "lead_owner": "Manish Chauhan",
      "company": "Rangoni Of Florence",
      "first_name": "Christopher",
      "last_name": "Maclead",
      "title": "VP Accounting",
      "email": "christopher-maclead@gmail.com",
      "fax": "",
      "phone": "555-555-5555",
      "mobile": "555-555-5555",
      "website": "http://www.chapmanrosseesq.com",
      "lead_source": "Online Store",
      "lead_status": "Attempted to Contact",
      "industry": "Storage Equipment",
      "no_of_employees": 0,
      "annual_revenue": 0,
      "rating": 0,
      "email_opt_out": 0,
      "skype_id": "felix-hirpara",
      "secondary_email": "string",
      "twitter": "felixhirpara_sample",
      "street": "3 Mcauley Dr",
      "city": "Ashland",
      "state": "OH",
      "zipcode": "44805",
      "country": "United States",
      "description": "",
      "created_by": "string"
    }
  }

  
  public vals: Array<leadListModel> = [
    {
      "lead_owner": "Manish Chauhan",
      "company": "Rangoni Of Florence",
      "first_name": "Christopher",
      "last_name": "Maclead",
      "title": "VP Accounting",
      "email": "christopher-maclead@gmail.com",
      "fax": "",
      "phone": "555-555-5555",
      "mobile": "555-555-5555",
      "website": "http://www.chapmanrosseesq.com",
      "lead_source": "Online Store",
      "lead_status": "Attempted to Contact",
      "industry": "Storage Equipment",
      "no_of_employees": 0,
      "annual_revenue": 0,
      "rating": 0,
      "email_opt_out": 0,
      "skype_id": "felix-hirpara",
      "secondary_email": "string",
      "twitter": "felixhirpara_sample",
      "street": "3 Mcauley Dr",
      "city": "Ashland",
      "state": "OH",
      "zipcode": "44805",
      "country": "United States",
      "description": "",
      "created_by": "string"
    },
    {
      "lead_owner": "Manish Chauhan",
      "company": "Rangoni Of Florence",
      "first_name": "Christopher",
      "last_name": "Maclead",
      "title": "VP Accounting",
      "email": "christopher-maclead@gmail.com",
      "fax": "",
      "phone": "555-555-5555",
      "mobile": "555-555-5555",
      "website": "http://www.chapmanrosseesq.com",
      "lead_source": "Online Store",
      "lead_status": "Attempted to Contact",
      "industry": "Storage Equipment",
      "no_of_employees": 0,
      "annual_revenue": 0,
      "rating": 3,
      "email_opt_out": 0,
      "skype_id": "felix-hirpara",
      "secondary_email": "string",
      "twitter": "felixhirpara_sample",
      "street": "3 Mcauley Dr",
      "city": "Ashland",
      "state": "OH",
      "zipcode": "44805",
      "country": "United States",
      "description": "",
      "created_by": "string"
    },
    {
      "lead_owner": "Manish Chauhan",
      "company": "Rangoni Of Florence",
      "first_name": "Christopher",
      "last_name": "Maclead",
      "title": "VP Accounting",
      "email": "christopher-maclead@gmail.com",
      "fax": "",
      "phone": "555-555-5555",
      "mobile": "555-555-5555",
      "website": "http://www.chapmanrosseesq.com",
      "lead_source": "Online Store",
      "lead_status": "Attempted to Contact",
      "industry": "Storage Equipment",
      "no_of_employees": 0,
      "annual_revenue": 0,
      "rating": 5,
      "email_opt_out": 0,
      "skype_id": "felix-hirpara",
      "secondary_email": "string",
      "twitter": "felixhirpara_sample",
      "street": "3 Mcauley Dr",
      "city": "Ashland",
      "state": "OH",
      "zipcode": "44805",
      "country": "United States",
      "description": "",
      "created_by": "string"
    },
    {
      "lead_owner": "Manish Chauhan",
      "company": "Rangoni Of Florence",
      "first_name": "Christopher",
      "last_name": "Maclead",
      "title": "VP Accounting",
      "email": "christopher-maclead@gmail.com",
      "fax": "",
      "phone": "555-555-5555",
      "mobile": "555-555-5555",
      "website": "http://www.chapmanrosseesq.com",
      "lead_source": "Online Store",
      "lead_status": "Attempted to Contact",
      "industry": "Storage Equipment",
      "no_of_employees": 0,
      "annual_revenue": 0,
      "rating": 1,
      "email_opt_out": 0,
      "skype_id": "felix-hirpara",
      "secondary_email": "string",
      "twitter": "felixhirpara_sample",
      "street": "3 Mcauley Dr",
      "city": "Ashland",
      "state": "OH",
      "zipcode": "44805",
      "country": "United States",
      "description": "",
      "created_by": "string"
    },
    {
      "lead_owner": "Manish Chauhan",
      "company": "Rangoni Of Florence",
      "first_name": "Christopher",
      "last_name": "Maclead",
      "title": "VP Accounting",
      "email": "christopher-maclead@gmail.com",
      "fax": "",
      "phone": "555-555-5555",
      "mobile": "555-555-5555",
      "website": "http://www.chapmanrosseesq.com",
      "lead_source": "Online Store",
      "lead_status": "Attempted to Contact",
      "industry": "Storage Equipment",
      "no_of_employees": 0,
      "annual_revenue": 0,
      "rating": 9,
      "email_opt_out": 0,
      "skype_id": "felix-hirpara",
      "secondary_email": "string",
      "twitter": "felixhirpara_sample",
      "street": "3 Mcauley Dr",
      "city": "Ashland",
      "state": "OH",
      "zipcode": "44805",
      "country": "United States",
      "description": "",
      "created_by": "string"
    },
    {
      "lead_owner": "Manish Chauhan",
      "company": "Rangoni Of Florence",
      "first_name": "Christopher",
      "last_name": "Maclead",
      "title": "VP Accounting",
      "email": "christopher-maclead@gmail.com",
      "fax": "",
      "phone": "555-555-5555",
      "mobile": "555-555-5555",
      "website": "http://www.chapmanrosseesq.com",
      "lead_source": "Online Store",
      "lead_status": "Attempted to Contact",
      "industry": "Storage Equipment",
      "no_of_employees": 0,
      "annual_revenue": 0,
      "rating": 4,
      "email_opt_out": 0,
      "skype_id": "felix-hirpara",
      "secondary_email": "string",
      "twitter": "felixhirpara_sample",
      "street": "3 Mcauley Dr",
      "city": "Ashland",
      "state": "OH",
      "zipcode": "44805",
      "country": "United States",
      "description": "",
      "created_by": "string"
    },
    {
      "lead_owner": "Manish Chauhan",
      "company": "Rangoni Of Florence",
      "first_name": "Christopher",
      "last_name": "Maclead",
      "title": "VP Accounting",
      "email": "christopher-maclead@gmail.com",
      "fax": "",
      "phone": "555-555-5555",
      "mobile": "555-555-5555",
      "website": "http://www.chapmanrosseesq.com",
      "lead_source": "Online Store",
      "lead_status": "Attempted to Contact",
      "industry": "Storage Equipment",
      "no_of_employees": 0,
      "annual_revenue": 0,
      "rating": 6,
      "email_opt_out": 0,
      "skype_id": "felix-hirpara",
      "secondary_email": "string",
      "twitter": "felixhirpara_sample",
      "street": "3 Mcauley Dr",
      "city": "Ashland",
      "state": "OH",
      "zipcode": "44805",
      "country": "United States",
      "description": "",
      "created_by": "string"
    },
    {
      "lead_owner": "Manish Chauhan",
      "company": "Rangoni Of Florence",
      "first_name": "Christopher",
      "last_name": "Maclead",
      "title": "VP Accounting",
      "email": "christopher-maclead@gmail.com",
      "fax": "",
      "phone": "555-555-5555",
      "mobile": "555-555-5555",
      "website": "http://www.chapmanrosseesq.com",
      "lead_source": "Online Store",
      "lead_status": "Attempted to Contact",
      "industry": "Storage Equipment",
      "no_of_employees": 0,
      "annual_revenue": 0,
      "rating": 4,
      "email_opt_out": 0,
      "skype_id": "felix-hirpara",
      "secondary_email": "string",
      "twitter": "felixhirpara_sample",
      "street": "3 Mcauley Dr",
      "city": "Ashland",
      "state": "OH",
      "zipcode": "44805",
      "country": "United States",
      "description": "",
      "created_by": "string"
    },
    {
      "lead_owner": "Manish Chauhan",
      "company": "Rangoni Of Florence",
      "first_name": "Christopher",
      "last_name": "Maclead",
      "title": "VP Accounting",
      "email": "christopher-maclead@gmail.com",
      "fax": "",
      "phone": "555-555-5555",
      "mobile": "555-555-5555",
      "website": "http://www.chapmanrosseesq.com",
      "lead_source": "Online Store",
      "lead_status": "Attempted to Contact",
      "industry": "Storage Equipment",
      "no_of_employees": 0,
      "annual_revenue": 0,
      "rating": 8,
      "email_opt_out": 0,
      "skype_id": "felix-hirpara",
      "secondary_email": "string",
      "twitter": "felixhirpara_sample",
      "street": "3 Mcauley Dr",
      "city": "Ashland",
      "state": "OH",
      "zipcode": "44805",
      "country": "United States",
      "description": "",
      "created_by": "string"
    },
    {
      "lead_owner": "Manish Chauhan",
      "company": "Rangoni Of Florence",
      "first_name": "Christopher",
      "last_name": "Maclead",
      "title": "VP Accounting",
      "email": "christopher-maclead@gmail.com",
      "fax": "",
      "phone": "555-555-5555",
      "mobile": "555-555-5555",
      "website": "http://www.chapmanrosseesq.com",
      "lead_source": "Online Store",
      "lead_status": "Attempted to Contact",
      "industry": "Storage Equipment",
      "no_of_employees": 0,
      "annual_revenue": 0,
      "rating": 3,
      "email_opt_out": 0,
      "skype_id": "felix-hirpara",
      "secondary_email": "string",
      "twitter": "felixhirpara_sample",
      "street": "3 Mcauley Dr",
      "city": "Ashland",
      "state": "OH",
      "zipcode": "44805",
      "country": "United States",
      "description": "",
      "created_by": "string"
    },
    {
      "lead_owner": "Manish Chauhan",
      "company": "Rangoni Of Florence",
      "first_name": "Christopher",
      "last_name": "Maclead",
      "title": "VP Accounting",
      "email": "christopher-maclead@gmail.com",
      "fax": "",
      "phone": "555-555-5555",
      "mobile": "555-555-5555",
      "website": "http://www.chapmanrosseesq.com",
      "lead_source": "Online Store",
      "lead_status": "Attempted to Contact",
      "industry": "Storage Equipment",
      "no_of_employees": 0,
      "annual_revenue": 0,
      "rating": 7,
      "email_opt_out": 0,
      "skype_id": "felix-hirpara",
      "secondary_email": "string",
      "twitter": "felixhirpara_sample",
      "street": "3 Mcauley Dr",
      "city": "Ashland",
      "state": "OH",
      "zipcode": "44805",
      "country": "United States",
      "description": "",
      "created_by": "string"
    },
    {
      "lead_owner": "Manish Chauhan",
      "company": "Rangoni Of Florence",
      "first_name": "Christopher",
      "last_name": "Maclead",
      "title": "VP Accounting",
      "email": "christopher-maclead@gmail.com",
      "fax": "",
      "phone": "555-555-5555",
      "mobile": "555-555-5555",
      "website": "http://www.chapmanrosseesq.com",
      "lead_source": "Online Store",
      "lead_status": "Attempted to Contact",
      "industry": "Storage Equipment",
      "no_of_employees": 0,
      "annual_revenue": 0,
      "rating": 8,
      "email_opt_out": 0,
      "skype_id": "felix-hirpara",
      "secondary_email": "string",
      "twitter": "felixhirpara_sample",
      "street": "3 Mcauley Dr",
      "city": "Ashland",
      "state": "OH",
      "zipcode": "44805",
      "country": "United States",
      "description": "",
      "created_by": "string"
    },
    {
      "lead_owner": "Manish Chauhan",
      "company": "Rangoni Of Florence",
      "first_name": "Christopher",
      "last_name": "Maclead",
      "title": "VP Accounting",
      "email": "christopher-maclead@gmail.com",
      "fax": "",
      "phone": "555-555-5555",
      "mobile": "555-555-5555",
      "website": "http://www.chapmanrosseesq.com",
      "lead_source": "Online Store",
      "lead_status": "Attempted to Contact",
      "industry": "Storage Equipment",
      "no_of_employees": 0,
      "annual_revenue": 0,
      "rating": 9,
      "email_opt_out": 0,
      "skype_id": "felix-hirpara",
      "secondary_email": "string",
      "twitter": "felixhirpara_sample",
      "street": "3 Mcauley Dr",
      "city": "Ashland",
      "state": "OH",
      "zipcode": "44805",
      "country": "United States",
      "description": "",
      "created_by": "string"
    },
    {
      "lead_owner": "Manish Chauhan",
      "company": "Rangoni Of Florence",
      "first_name": "Christopher",
      "last_name": "Maclead",
      "title": "VP Accounting",
      "email": "christopher-maclead@gmail.com",
      "fax": "",
      "phone": "555-555-5555",
      "mobile": "555-555-5555",
      "website": "http://www.chapmanrosseesq.com",
      "lead_source": "Online Store",
      "lead_status": "Attempted to Contact",
      "industry": "Storage Equipment",
      "no_of_employees": 0,
      "annual_revenue": 0,
      "rating": 6,
      "email_opt_out": 0,
      "skype_id": "felix-hirpara",
      "secondary_email": "string",
      "twitter": "felixhirpara_sample",
      "street": "3 Mcauley Dr",
      "city": "Ashland",
      "state": "OH",
      "zipcode": "44805",
      "country": "United States",
      "description": "",
      "created_by": "string"
    },
    {
      "lead_owner": "Manish Chauhan",
      "company": "Rangoni Of Florence",
      "first_name": "Christopher",
      "last_name": "Maclead",
      "title": "VP Accounting",
      "email": "christopher-maclead@gmail.com",
      "fax": "",
      "phone": "555-555-5555",
      "mobile": "555-555-5555",
      "website": "http://www.chapmanrosseesq.com",
      "lead_source": "Online Store",
      "lead_status": "Attempted to Contact",
      "industry": "Storage Equipment",
      "no_of_employees": 0,
      "annual_revenue": 0,
      "rating": 5,
      "email_opt_out": 0,
      "skype_id": "felix-hirpara",
      "secondary_email": "string",
      "twitter": "felixhirpara_sample",
      "street": "3 Mcauley Dr",
      "city": "Ashland",
      "state": "OH",
      "zipcode": "44805",
      "country": "United States",
      "description": "",
      "created_by": "string"
    },
    {
      "lead_owner": "Manish Chauhan",
      "company": "Rangoni Of Florence",
      "first_name": "Christopher",
      "last_name": "Maclead",
      "title": "VP Accounting",
      "email": "christopher-maclead@gmail.com",
      "fax": "",
      "phone": "555-555-5555",
      "mobile": "555-555-5555",
      "website": "http://www.chapmanrosseesq.com",
      "lead_source": "Online Store",
      "lead_status": "Attempted to Contact",
      "industry": "Storage Equipment",
      "no_of_employees": 0,
      "annual_revenue": 0,
      "rating": 2,
      "email_opt_out": 0,
      "skype_id": "felix-hirpara",
      "secondary_email": "string",
      "twitter": "felixhirpara_sample",
      "street": "3 Mcauley Dr",
      "city": "Ashland",
      "state": "OH",
      "zipcode": "44805",
      "country": "United States",
      "description": "",
      "created_by": "string"
    }
  ]

}
